"""适配器抽象层。"""

from .message import (
    MessageAdapter,
    build_message,
    build_message_segment,
    event_message,
    extract_first_text_match,
    extract_image_sources,
    extract_raw_image_sources,
    extract_message_target,
    extract_reply_message_id,
    first_mention_target,
    get_message_adapter,
    get_onebot_v11_message_segment_class,
    get_replied_message,
    is_mention_segment,
    is_onebot_v11,
    is_qq_official,
    is_text_segment,
    mention_target,
    mention_targets,
    move_non_text_segments_to_end,
    register_message_adapter,
    send_forward_messages,
    send_forward_texts,
    send_ark_message,
    send_message_to_target,
    send_text_to_target,
)
from .images import (
    fetch_image_bytes,
    image_sources_from_event_or_reply,
)
from .onebot11 import OneBotV11MessageAdapter
from .qq import QQOfficialMessageAdapter

__all__ = [
    "MessageAdapter",
    "OneBotV11MessageAdapter",
    "QQOfficialMessageAdapter",
    "build_message",
    "build_message_segment",
    "event_message",
    "extract_first_text_match",
    "extract_image_sources",
    "extract_raw_image_sources",
    "extract_message_target",
    "extract_reply_message_id",
    "fetch_image_bytes",
    "first_mention_target",
    "get_message_adapter",
    "get_onebot_v11_message_segment_class",
    "get_replied_message",
    "image_sources_from_event_or_reply",
    "is_mention_segment",
    "is_onebot_v11",
    "is_qq_official",
    "is_text_segment",
    "mention_target",
    "mention_targets",
    "move_non_text_segments_to_end",
    "register_message_adapter",
    "send_forward_messages",
    "send_forward_texts",
    "send_message_to_target",
    "send_ark_message",
    "send_text_to_target",
]
